;;; run-tests.el --- Run Emacsvox tests in batch mode -*- lexical-binding: t; -*-

;;; Commentary:

;; Batch entry point for the Emacsvox ERT suite.

;;; Code:

(require 'ert)

(when (< emacs-major-version 31)
  (error "Emacsvox tests require Emacs 31 or later"))

(setq load-prefer-newer t)

(let* ((test-directory
        (file-name-directory (or load-file-name buffer-file-name)))
       (root-directory (expand-file-name "../" test-directory))
       (lisp-directory (expand-file-name "lisp/" root-directory))
       (utils-directory (expand-file-name "utils/" root-directory)))
  (add-to-list 'load-path test-directory)
  (add-to-list 'load-path lisp-directory)
  (add-to-list 'load-path utils-directory)
  ;; Load source explicitly so tests never exercise a stale .elc file.
  (load (expand-file-name "emacsvox-preamble.el" lisp-directory)
        nil nil)
  (require 'emacsvox-advice-tests)
  (require 'emacsvox-advice-audit-tests)
  (require 'emacsvox-converter-tests)
  (require 'emacsvox-dired-tests)
  (require 'emacsvox-mail-tests)
  (require 'emacsvox-core-migration-tests)
  (require 'emacsvox-completion-tests)
  (require 'emacsvox-input-tests)
  (require 'emacsvox-search-tests)
  (require 'emacsvox-file-tests)
  (require 'emacsvox-process-tests)
  (require 'emacsvox-vc-tests)
  (require 'emacsvox-overlay-tests)
  (require 'emacsvox-message-tests)
  (require 'emacsvox-timer-tests)
  (require 'emacsvox-navigation-tests)
  (require 'emacsvox-rectangle-tests)
  (require 'emacsvox-register-tests)
  (require 'emacsvox-button-tests)
  (require 'emacsvox-tooltip-tests)
  (require 'emacsvox-formatting-tests)
  (require 'emacsvox-help-tests)
  (require 'emacsvox-region-tests)
  (require 'emacsvox-eval-tests)
  (require 'emacsvox-narrowing-tests)
  (require 'emacsvox-undo-tests)
  (require 'emacsvox-position-tests)
  (require 'emacsvox-mark-tests)
  (require 'emacsvox-cleanup-tests)
  (require 'emacsvox-elint-tests)
  (require 'emacsvox-browser-tests)
  (require 'emacsvox-splash-tests)
  (require 'emacsvox-copyright-tests)
  (require 'emacsvox-keyboard-macro-tests)
  (require 'emacsvox-transpose-tests)
  (require 'emacsvox-toggle-tests)
  (require 'emacsvox-abbrev-tests)
  (require 'emacsvox-finder-tests)
  (require 'emacsvox-server-tests)
  (require 'emacsvox-customize-tests)
  (require 'emacsvox-editing-tests)
  (require 'emacsvox-display-tests)
  (require 'emacsvox-spinner-tests)
  (require 'emacsvox-key-definition-tests)
  (require 'emacsvox-suspend-tests)
  (require 'emacsvox-ange-ftp-tests)
  (require 'emacsvox-compile-tests)
  (require 'emacsvox-windmove-tests)
  (require 'emacsvox-ffap-tests)
  (require 'emacsvox-ido-tests)
  (require 'emacsvox-diff-mode-tests)
  (require 'emacsvox-project-tests)
  (require 'emacsvox-flymake-tests)
  (require 'emacsvox-package-tests)
  (require 'emacsvox-info-tests)
  (require 'emacsvox-debugger-tests)
  (require 'emacsvox-etable-tests)
  (require 'emacsvox-proced-tests)
  (require 'emacsvox-view-tests)
  (require 'emacsvox-calendar-tests)
  (require 'emacsvox-wdired-tests)
  (require 'emacsvox-tabulated-list-tests)
  (require 'emacsvox-net-utils-tests)
  (require 'emacsvox-forms-tests)
  (require 'emacsvox-xref-tests)
  (require 'emacsvox-org-tests)
  (require 'emacsvox-outline-tests)
  (require 'emacsvox-eww-tests)
  (require 'emacsvox-gnus-tests)
  (require 'emacsvox-ibuffer-tests)
  (require 'emacsvox-comint-tests)
  (require 'emacsvox-tab-bar-tests)
  (require 'emacsvox-c-tests)
  (require 'emacsvox-eshell-tests)
  (require 'emacsvox-which-key-tests)
  (require 'emacsvox-eterm-tests)
  (require 'emacsvox-ispell-tests)
  (require 'emacsvox-widget-tests)
  (require 'emacsvox-rst-tests)
  (require 'emacsvox-reftex-tests)
  (require 'emacsvox-bs-tests)
  (require 'emacsvox-bibtex-tests)
  (require 'emacsvox-bookmark-tests)
  (require 'emacsvox-posting-message-tests)
  (require 'emacsvox-calculator-tests)
  (require 'emacsvox-buff-menu-tests)
  (require 'emacsvox-rmail-tests)
  (require 'emacsvox-custom-ui-tests)
  (require 'emacsvox-ediff-tests)
  (require 'emacsvox-tetris-tests)
  (require 'emacsvox-cperl-tests)
  (require 'emacsvox-cmuscheme-tests)
  (require 'emacsvox-speedbar-tests)
  (require 'emacsvox-tcl-tests)
  (require 'emacsvox-man-tests)
  (require 'emacsvox-python-tests)
  (require 'emacsvox-make-mode-tests)
  (require 'emacsvox-dictionary-tests)
  (require 'emacsvox-transient-tests)
  (require 'emacsvox-arc-tests)
  (require 'emacsvox-tar-tests)
  (require 'emacsvox-sh-script-tests)
  (require 'emacsvox-re-builder-tests)
  (require 'emacsvox-kmacro-tests)
  (require 'emacsvox-hideshow-tests)
  (require 'emacsvox-nxml-tests)
  (require 'emacsvox-epa-tests)
  (require 'emacsvox-ruby-tests)
  (require 'emacsvox-erc-tests)
  (require 'emacsvox-info-tests)
  (require 'emacsvox-solitaire-tests)
  (require 'emacsvox-sql-tests)
  (require 'emacsvox-flyspell-tests)
  (require 'emacsvox-supercite-tests)
  (require 'emacsvox-lua-tests)
  (require 'emacsvox-sgml-mode-tests)
  (require 'emacsvox-newsticker-tests)
  (require 'emacsvox-calc-tests)
  (require 'emacsvox-gomoku-tests)
  (require 'emacsvox-eudc-tests)
  (require 'emacsvox-texinfo-tests)
  (require 'emacsvox-desktop-tests)
  (require 'emacsvox-ses-tests)
  (require 'emacsvox-tempo-tests)
  (require 'emacsvox-woman-tests)
  (require 'emacsvox-eglot-tests)
  (require 'emacsvox-enriched-tests)
  (require 'emacsvox-gud-tests)
  (require 'emacsvox-perl-tests)
  (require 'emacsvox-todo-mode-tests)
  (require 'emacsvox-treesit-tests)
  (require 'emacsvox-entertain-tests)
  (require 'emacsvox-browse-kill-ring-tests)
  (require 'emacsvox-company-tests)
  (require 'emacsvox-helm-tests)
  (require 'emacsvox-hydra-tests)
  (require 'emacsvox-pydoc-tests)
  (require 'emacsvox-yaml-tests)
  (require 'emacsvox-flycheck-tests)
  (require 'emacsvox-folding-tests)
  (require 'emacsvox-github-explorer-tests)
  (require 'emacsvox-ivy-tests)
  (require 'emacsvox-magit-tests)
  (require 'emacsvox-marginalia-tests)
  (require 'emacsvox-yasnippet-tests)
  (require 'emacsvox-syslog-tests)
  (require 'emacsvox-rust-mode-tests)
  (require 'emacsvox-markdown-tests)
  (require 'emacsvox-maths-tests)
  (require 'emacsvox-py-tests)
  (require 'emacsvox-2048-tests)
  (require 'emacsvox-abc-mode-tests)
  (require 'emacsvox-ace-window-tests)
  (require 'emacsvox-annotate-tests)
  (require 'emacsvox-auctex-tests)
  (require 'emacsvox-avy-tests)
  (require 'emacsvox-bbdb-tests)
  (require 'emacsvox-calibredb-tests)
  (require 'emacsvox-chess-tests)
  (require 'emacsvox-cider-tests)
  (require 'emacsvox-clojure-tests)
  (require 'emacsvox-combobulate-tests)
  (require 'emacsvox-consult-tests)
  (require 'emacsvox-corfu-tests)
  (require 'emacsvox-deadgrep-tests)
  (require 'emacsvox-denote-tests)
  (require 'emacsvox-devdocs-tests)
  (require 'emacsvox-dumb-jump-tests)
  (require 'emacsvox-eat-tests)
  (require 'emacsvox-ebuku-tests)
  (require 'emacsvox-ein-tests)
  (require 'emacsvox-elfeed-tests)
  (require 'emacsvox-elisp-refs-tests)
  (require 'emacsvox-ellama-tests)
  (require 'emacsvox-elpher-tests)
  (require 'emacsvox-elpy-tests)
  (require 'emacsvox-embark-tests)
  (require 'emacsvox-emms-tests)
  (require 'emacsvox-empv-tests)
  (require 'emacsvox-enwc-tests)
  (require 'emacsvox-ess-tests)
  (require 'emacsvox-evil-tests)
  (require 'emacsvox-exwm-tests)
  (require 'emacsvox-ffip-tests)
  (require 'emacsvox-forge-tests)
  (require 'emacsvox-geiser-tests)
  (require 'emacsvox-go-mode-tests)
  (require 'emacsvox-gnuplot-tests)
  (require 'emacsvox-gptel-tests)
  (require 'emacsvox-google-tests)
  (require 'emacsvox-haskell-tests)
  (require 'emacsvox-helpful-tests)
  (require 'emacsvox-hide-lines-tests)
  (require 'emacsvox-iedit-tests)
  (require 'emacsvox-journalctl-tests)
  (require 'emacsvox-js2-tests)
  (require 'emacsvox-lispy-tests)
  (require 'emacsvox-mines-tests)
  (require 'emacsvox-mu4e-tests)
  (require 'emacsvox-multiple-cursors-tests)
  (require 'emacsvox-muse-tests)
  (require 'emacsvox-notmuch-tests)
  (require 'emacsvox-nov-tests)
  (require 'emacsvox-orgalist-tests)
  (require 'emacsvox-paradox-tests)
  (require 'emacsvox-pipewire-tests)
  (require 'emacsvox-popup-tests)
  (require 'emacsvox-projectile-tests)
  (require 'emacsvox-racket-tests)
  (require 'emacsvox-related-tests)
  (require 'emacsvox-rg-tests)
  (require 'emacsvox-rpm-spec-tests)
  (require 'emacsvox-sage-tests)
  (require 'emacsvox-sdcv-tests)
  (require 'emacsvox-slime-tests)
  (require 'emacsvox-smartparens-tests)
  (require 'emacsvox-sox-tests)
  (require 'emacsvox-sudoku-tests)
  (require 'emacsvox-threes-tests)
  (require 'emacsvox-typo-tests)
  (require 'emacsvox-vdiff-tests)
  (require 'emacsvox-vertico-tests)
  (require 'emacsvox-vterm-tests)
  (require 'emacsvox-we-tests)
  (require 'emacsvox-wizards-tests)
  (require 'emacsvox-xkcd-tests)
  (require 'gweb-tests)
  (require 'emacsvox-trace-tests))

(ert-run-tests-batch-and-exit)

;;; run-tests.el ends here
