;;; emacsvox-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from amixer.el

(autoload 'amixer "amixer" "\
ALSA settings.
Interactive prefix arg refreshes cache.

(fn &optional REFRESH)" t)
(autoload 'amixer-volume-adjust "amixer" "\
Adjust volume continuously.
Press C-e 3 to lower volume; C-e 4 to increase it. Subsequent presses
of 3 and 4 lower or raise volume." t)
(register-definition-prefixes "amixer" '("amixer-"))


;;; Generated autoloads from dectalk-voices.el

(autoload 'dectalk "dectalk-voices" "\
Dectalk TTS." t)
(autoload 'dectalk-soft "dectalk-voices" "\
Software Dectalk TTS." t)
(autoload 'dectalk-configure-tts "dectalk-voices" "\
Configures   to use Dectalk.")
(register-definition-prefixes "dectalk-voices" '("dectalk-"))


;;; Generated autoloads from dom-addons.el

(register-definition-prefixes "dom-addons" '("dom-"))


;;; Generated autoloads from dtk-speak.el

(register-definition-prefixes "dtk-speak" '("dtk-" "ems-" "tts-"))


;;; Generated autoloads from emacsvox.el

(defsubst emacsvox-setup-programming-mode nil "\
Setup programming mode." (dtk-set-punctuations 'all) (or dtk-split-caps (dtk-toggle-split-caps)) (or dtk-caps (dtk-toggle-caps)) (emacsvox-pronounce-refresh-pronunciations) (or emacsvox-audio-indentation (emacsvox-toggle-audio-indentation)))
(register-definition-prefixes "emacsvox" '("emacsvox-"))


;;; Generated autoloads from emacsvox-2048.el

(register-definition-prefixes "emacsvox-2048" '("emacsvox-2048-" "ems--2048-insert-random-cell-after"))


;;; Generated autoloads from emacsvox-advice.el

(register-definition-prefixes "emacsvox-advice" '("emacsvox-" "ems-"))


;;; Generated autoloads from emacsvox-amark.el

(register-definition-prefixes "emacsvox-amark" '("emacsvox-amark-"))


;;; Generated autoloads from emacsvox-analog.el

(register-definition-prefixes "emacsvox-analog" '("emacsvox-analog-" "ems--analog-"))


;;; Generated autoloads from emacsvox-annotate.el

(register-definition-prefixes "emacsvox-annotate" '("ems--annotate-annotate-after"))


;;; Generated autoloads from emacsvox-arc.el

(register-definition-prefixes "emacsvox-arc" '("emacsvox-arc" "ems--archive-"))


;;; Generated autoloads from emacsvox-auctex.el

(register-definition-prefixes "emacsvox-auctex" '("emacsvox-auctex-" "ems--"))


;;; Generated autoloads from emacsvox-autoload.el

(register-definition-prefixes "emacsvox-autoload" '("emacsvox-auto-"))


;;; Generated autoloads from emacsvox-bbdb.el

(register-definition-prefixes "emacsvox-bbdb" '("ems--bbdb"))


;;; Generated autoloads from emacsvox-bibtex.el

(register-definition-prefixes "emacsvox-bibtex" '("ems--"))


;;; Generated autoloads from emacsvox-bookmark.el

(register-definition-prefixes "emacsvox-bookmark" '("ems--bookmark-"))


;;; Generated autoloads from emacsvox-bookshare.el

(autoload 'emacsvox-bookshare "emacsvox-bookshare" "\
Bookshare  Interaction." t)
(autoload 'emacsvox-bookshare-eww "emacsvox-bookshare" "\
Render  book using EWW

(fn DIRECTORY)" t)
(register-definition-prefixes "emacsvox-bookshare" '("emacsvox-bookshare-"))


;;; Generated autoloads from emacsvox-browse-kill-ring.el

(register-definition-prefixes "emacsvox-browse-kill-ring" '("ems--browse-kill-ring-"))


;;; Generated autoloads from emacsvox-bs.el

(register-definition-prefixes "emacsvox-bs" '("emacsvox-bs-speak-buffer-line" "ems--bs-"))


;;; Generated autoloads from emacsvox-buff-menu.el

(register-definition-prefixes "emacsvox-buff-menu" '("emacsvox-list-buffers-" "ems--"))


;;; Generated autoloads from emacsvox-c.el

(register-definition-prefixes "emacsvox-c" '("c-" "emacsvox-c-s" "ems--c-"))


;;; Generated autoloads from emacsvox-calc.el

(register-definition-prefixes "emacsvox-calc" '("ems--calc-"))


;;; Generated autoloads from emacsvox-calculator.el

(register-definition-prefixes "emacsvox-calculator" '("emacsvox-calculator-summarize" "ems--calculator-"))


;;; Generated autoloads from emacsvox-calendar.el

(register-definition-prefixes "emacsvox-calendar" '("emacsvox-" "ems--"))


;;; Generated autoloads from emacsvox-calibredb.el

(register-definition-prefixes "emacsvox-calibredb" '("emacsvox-calibredb-" "ems--calibredb-"))


;;; Generated autoloads from emacsvox-chess.el

(register-definition-prefixes "emacsvox-chess" '("chess-" "emacsvox-chess-" "ems--chess-display-"))


;;; Generated autoloads from emacsvox-cider.el

(register-definition-prefixes "emacsvox-cider" '("ems--cider-"))


;;; Generated autoloads from emacsvox-ciel.el

(register-definition-prefixes "emacsvox-ciel" '("ems--ciel-c"))


;;; Generated autoloads from emacsvox-clojure.el

(register-definition-prefixes "emacsvox-clojure" '("ems--clojure-"))


;;; Generated autoloads from emacsvox-cmuscheme.el

(register-definition-prefixes "emacsvox-cmuscheme" '("ems--"))


;;; Generated autoloads from emacsvox-combobulate.el

(register-definition-prefixes "emacsvox-combobulate" '("emacsvox-combobulate-speak-line"))


;;; Generated autoloads from emacsvox-comint.el

(defvar emacsvox-comint-autospeak nil "\
Speak comint output.
Use \\[emacsvox-toggle-comint-autospeak] to toggle this
setting. Do not set this globally. Also see custom option
`emacsvox-wizards-project-shells' for starting up
project-specific shells that have autospeak turned on. The
default is intentionally nil, since this option should only be
turned on where needed.")
(custom-autoload 'emacsvox-comint-autospeak "emacsvox-comint" t)
(autoload 'emacsvox-toggle-inaudible-or-comint-autospeak "emacsvox-comint" "\
Toggle comint-autospeak when in a comint or vterm buffer.
Otherwise call voice-setup-toggle-silence-personality which
toggles personality under point." t)
(ems-generate-switcher 'emacsvox-toggle-comint-output-monitor 'emacsvox-comint-output-monitor "\
Toggle  Emacsvox comint monitor.
Interactive PREFIX arg means toggle the global default value. ")
(autoload 'emacsvox-comint-speech-setup "emacsvox-comint" "\
Speech setup.")
(autoload 'emacsvox-zoxide "emacsvox-comint" "\
Query zoxide  and launch dired.
Shell Utility zoxide --- implemented in Rust --- lets you jump to
directories that are used often. 

(fn Q)" t)
(register-definition-prefixes "emacsvox-comint" '("dirtrack-procfs-mode" "emacsvox-" "ems--"))


;;; Generated autoloads from emacsvox-company.el

(register-definition-prefixes "emacsvox-company" '("emacsvox-company-" "ems-"))


;;; Generated autoloads from emacsvox-compile.el

(register-definition-prefixes "emacsvox-compile" '("emacsvox-compilation-speak-error" "ems--compil"))


;;; Generated autoloads from emacsvox-consult.el

(register-definition-prefixes "emacsvox-consult" '("emacsvox-consult-keymap"))


;;; Generated autoloads from emacsvox-cperl.el

(register-definition-prefixes "emacsvox-cperl" '("ems--cperl-"))


;;; Generated autoloads from emacsvox-custom.el

(register-definition-prefixes "emacsvox-custom" '("emacsvox-custom-" "ems--"))


;;; Generated autoloads from emacsvox-dbus.el

(autoload 'emacsvox-dbus-setup "emacsvox-dbus" "\
Turn on DBus handlers.")
(register-definition-prefixes "emacsvox-dbus" '("emacsvox-"))


;;; Generated autoloads from emacsvox-deadgrep.el

(register-definition-prefixes "emacsvox-deadgrep" '("ems--deadgrep-"))


;;; Generated autoloads from emacsvox-debugger.el

(register-definition-prefixes "emacsvox-debugger" '("ems--debugger-"))


;;; Generated autoloads from emacsvox-desktop.el

(autoload 'emacsvox-desktop-preserve "emacsvox-desktop" "\
Preserve: Dont kill this buffer when clearing desktop.

(fn BUFFER)" t)
(register-definition-prefixes "emacsvox-desktop" '("ems--desktop-"))


;;; Generated autoloads from emacsvox-dictionary.el

(register-definition-prefixes "emacsvox-dictionary" '("ems--dictionary-"))


;;; Generated autoloads from emacsvox-dired.el

(autoload 'emacsvox-find-dired "emacsvox-dired" "\
Prompt for find-dired arguments using context and completion." t)
(register-definition-prefixes "emacsvox-dired" '("emacsvox-" "ems--"))


;;; Generated autoloads from emacsvox-dismal.el

(register-definition-prefixes "emacsvox-dismal" '("emacsvox-dismal-" "ems--dis-html-dump-"))


;;; Generated autoloads from emacsvox-eat.el

(register-definition-prefixes "emacsvox-eat" '("emacsvox-eat-" "ems--eat-"))


;;; Generated autoloads from emacsvox-ebuku.el

(register-definition-prefixes "emacsvox-ebuku" '("ems--ebuku-"))


;;; Generated autoloads from emacsvox-ecb.el

(register-definition-prefixes "emacsvox-ecb" '("emacsvox-ecb-" "ems--" "tree-node-is-expanded"))


;;; Generated autoloads from emacsvox-ediff.el

(register-definition-prefixes "emacsvox-ediff" '("emacsvox-ediff-" "ems--ediff-"))


;;; Generated autoloads from emacsvox-eglot.el

(register-definition-prefixes "emacsvox-eglot" '("ems--eglot-help-at-point-after"))


;;; Generated autoloads from emacsvox-ein.el

(register-definition-prefixes "emacsvox-ein" '("emacsvox-ein-s" "ems--ein:"))


;;; Generated autoloads from emacsvox-elfeed.el

(register-definition-prefixes "emacsvox-elfeed" '("emacsvox-elfeed-" "ems--elfeed-"))


;;; Generated autoloads from emacsvox-ellama.el

(register-definition-prefixes "emacsvox-ellama" '("ems--ellama-chat-done-after"))


;;; Generated autoloads from emacsvox-elpy.el

(register-definition-prefixes "emacsvox-elpy" '("ems--elpy-"))


;;; Generated autoloads from emacsvox-elscreen.el

(register-definition-prefixes "emacsvox-elscreen" '("ems--elscreen-display-screen-name-list-around"))


;;; Generated autoloads from emacsvox-emms.el

(register-definition-prefixes "emacsvox-emms" '("emacsvox-emms-" "ems--emms-"))


;;; Generated autoloads from emacsvox-empv.el

(autoload 'emacsvox-empv-play-url "emacsvox-empv" "\
Play URL using mpv. 

(fn URL)" t)
(autoload 'emacsvox-empv-play-file "emacsvox-empv" "\
Play file using mpv.
Interactive prefix arg plays directory.
If already playing, then read an empv key and invoke its command.

(fn FILE &optional PREFIX)" t)
(autoload 'emacsvox-empv-yt-after "emacsvox-empv" "\
Youtube Search  from calendar --- add after:date-at-point.." t)
(register-definition-prefixes "emacsvox-empv" '("emacsvox-empv-" "ems--empv-"))


;;; Generated autoloads from emacsvox-enriched.el

(register-definition-prefixes "emacsvox-enriched" '("emacsvox-enriched-" "ems--enriched-"))


;;; Generated autoloads from emacsvox-entertain.el

(register-definition-prefixes "emacsvox-entertain" '("emacsvox-hangman-s" "ems--"))


;;; Generated autoloads from emacsvox-enwc.el

(register-definition-prefixes "emacsvox-enwc" '("ems--enwc-after"))


;;; Generated autoloads from emacsvox-epa.el

(register-definition-prefixes "emacsvox-epa" '("ems--epa-"))


;;; Generated autoloads from emacsvox-eperiodic.el

(register-definition-prefixes "emacsvox-eperiodic" '("emacsvox-eperiodic-" "ems--eperiodic-"))


;;; Generated autoloads from emacsvox-epub.el

(autoload 'emacsvox-epub "emacsvox-epub" "\
EPub  Interaction.
When opened, displays a bookshelf consisting of  epubs found at the
root directory,see \\[emacsvox-epub-mode]" t)
(autoload 'emacsvox-epub-eww "emacsvox-epub" "\
Display entire book  using EWW from EPub.
Use content listed in toc.ncx  if prefix-arg use-ncx is true.
Default is to  use   the sorted list of html files
in the epub file.

(fn EPUB-FILE &optional USE-NCX)" t)
(register-definition-prefixes "emacsvox-epub" '("emacsvox-" "epub-t"))


;;; Generated autoloads from emacsvox-erc.el

(register-definition-prefixes "emacsvox-erc" '("emacsvox-erc-" "ems--erc-"))


;;; Generated autoloads from emacsvox-eshell.el

(register-definition-prefixes "emacsvox-eshell" '("emacsvox-eshell-" "ems--eshell-"))


;;; Generated autoloads from emacsvox-ess.el

(register-definition-prefixes "emacsvox-ess" '("ems--ess-"))


;;; Generated autoloads from emacsvox-etable.el

(register-definition-prefixes "emacsvox-etable" '("emacsvox-etable-speak-cell" "ems--"))


;;; Generated autoloads from emacsvox-eterm.el

(register-definition-prefixes "emacsvox-eterm" '("eterm-"))


;;; Generated autoloads from emacsvox-eudc.el

(register-definition-prefixes "emacsvox-eudc" '("emacsvox-eudc-" "ems--eudc-"))


;;; Generated autoloads from emacsvox-evil.el

(register-definition-prefixes "emacsvox-evil" '("emacsvox-evil-" "ems--evil-"))


;;; Generated autoloads from emacsvox-eww.el

(defsubst emacsvox-eww-browser-check nil "\
Browser check" (cl-assert (eq major-mode 'eww-mode) t (error "Not in EWW")))
(autoload 'emacsvox-eww-autospeak "emacsvox-eww" "\
Setup post process hook to speak the first windowful . ")
(defvar emacsvox-eww-pre-process-hook nil "\
Pre-process hook -- to be used for XSL preprocessing etc.")
(defvar emacsvox-eww-shr-renderers '((article . emacsvox-eww-tag-article) (audio . emacsvox-eww-tag-audio) (iframe . emacsvox-eww-tag-iframe) (title . eww-tag-title) (video . emacsvox-eww-tag-video) (form . eww-tag-form) (input . eww-tag-input) (textarea . eww-tag-textarea) (math . shr-tag-math) (meta . eww-tag-meta) (button . eww-form-submit) (select . eww-tag-select) (link . eww-tag-link) (a . eww-tag-a)) "\
Customize shr rendering for EWW.")
(defvar emacsvox-eww-filter-renderers (let ((copy (copy-sequence emacsvox-eww-shr-renderers))) (cl-pushnew (cons 'em 'emacsvox-eww-em-with-space) copy) (cl-pushnew (cons 'strong 'emacsvox-eww-strong-with-space) copy) (cl-pushnew (cons 'span 'emacsvox-eww-span-with-space) copy) copy) "\
Renderers used when filtering.")
(autoload 'emacsvox-eww-open-mark "emacsvox-eww" "\
Open EWW marked location.  With optional interactive prefix
arg `delete', delete that mark instead.

(fn NAME &optional DELETE)" t)
(autoload 'emacsvox-eww-marks-browse "emacsvox-eww" "\
List EWW Marks as actionable buttons." t)
(autoload 'emacsvox-eww-smart-tabs "emacsvox-eww" "\
Open URL in EWW keyed by  `char'.
To associate a URL with a char, use this command
with an interactive prefix arg. 

(fn CHAR &optional DEFINE)" t)
(register-definition-prefixes "emacsvox-eww" '("eww-" "shr-tag-"))


;;; Generated autoloads from emacsvox-extras.el

(autoload 'emacsvox-wizards-midi-using-m-score "emacsvox-extras" "\
Play midi file using mscore from musescore package.

(fn MIDI-FILE)" t)
(autoload 'emacsvox-wizards-voice-sampler "emacsvox-extras" "\
Read a personality  and apply it to the current line.

(fn PERSONALITY)" t)
(autoload 'emacsvox-wizards-generate-voice-sampler "emacsvox-extras" "\
Generate a buffer that shows a sample line in all the ACSS settings
for the current voice family.

(fn STEP)" t)
(autoload 'emacsvox-wizards-show-voices "emacsvox-extras" "\
Display a buffer with sample text in the defined voices." t)
(autoload 'emacsvox-clipfile-copy "emacsvox-extras" "\
Use file-based Emacsvox Clipboard ---
dis a convenient way of sharing information between independent
Emacsvox sessions running on  different machines. 

(fn START END &optional PROMPT)" t)
(autoload 'emacsvox-clipfile-paste "emacsvox-extras" "\
Yank contents of the Emacsvox clipboard at point. 

(fn &optional PASTE-TABLE)" t)
(register-definition-prefixes "emacsvox-extras" '("emacsvox-" "ems--wizards-sampler-text" "voice-setup-"))


;;; Generated autoloads from emacsvox-exwm.el

(register-definition-prefixes "emacsvox-exwm" '("emacsvox-exwm-" "ems--exwm-"))


;;; Generated autoloads from emacsvox-feeds.el

(autoload 'emacsvox-feeds-add-feed "emacsvox-feeds" "\
Add specified feed to our feed store.

(fn TITLE URL TYPE)" t)
(autoload 'emacsvox-feeds-feed-display "emacsvox-feeds" "\
Fetch feed asynchronously via Emacs and display using xsltproc.

(fn FEED-URL STYLE &optional SPEAK)")
(autoload 'emacsvox-feeds-rss-display "emacsvox-feeds" "\
Display RSS feed.

(fn FEED-URL)" t)
(autoload 'emacsvox-feeds-opml-display "emacsvox-feeds" "\
Display OPML feed.

(fn FEED-URL)" t)
(autoload 'emacsvox-feeds-select-feed "emacsvox-feeds" "\
Prompt for feed-type (Atom, RSS, OPML and open it.

(fn FEED-TYPE)" t)
(autoload 'emacsvox-feeds-atom-display "emacsvox-feeds" "\
Display ATOM feed.

(fn FEED-URL)" t)
(autoload 'emacsvox-feeds-browse "emacsvox-feeds" "\
Browse   feed.

(fn FEED)" t)
(register-definition-prefixes "emacsvox-feeds" '("emacsvox-feeds"))


;;; Generated autoloads from emacsvox-filtertext.el

(autoload 'emacsvox-filtertext "emacsvox-filtertext" "\
Copy over text in region to special filtertext buffer to  filter text. 

(fn START END)" t)
(register-definition-prefixes "emacsvox-filtertext" '("emacsvox-filtertext-"))


;;; Generated autoloads from emacsvox-flycheck.el

(register-definition-prefixes "emacsvox-flycheck" '("ems--flycheck-"))


;;; Generated autoloads from emacsvox-flymake.el

(register-definition-prefixes "emacsvox-flymake" '("ems--flymake-compile-after"))


;;; Generated autoloads from emacsvox-flyspell.el

(register-definition-prefixes "emacsvox-flyspell" '("emacsvox-flyspell-correct" "ems--flyspell-"))


;;; Generated autoloads from emacsvox-folding.el

(register-definition-prefixes "emacsvox-folding" '("ems--folding-"))


;;; Generated autoloads from emacsvox-forms.el

(autoload 'emacsvox-forms-find-file "emacsvox-forms" "\
Visit a forms file

(fn FILENAME)" t)
(register-definition-prefixes "emacsvox-forms" '("emacsvox-forms-" "ems--forms-"))


;;; Generated autoloads from emacsvox-geiser.el

(register-definition-prefixes "emacsvox-geiser" '("ems--geiser-repl-"))


;;; Generated autoloads from emacsvox-gh-explorer.el

(register-definition-prefixes "emacsvox-gh-explorer" '("emacsvox-gh-explorer-" "ems--gh-explorer-nav"))


;;; Generated autoloads from emacsvox-gnuplot.el

(register-definition-prefixes "emacsvox-gnuplot" '("ems--gnuplot-"))


;;; Generated autoloads from emacsvox-gnus.el

(register-definition-prefixes "emacsvox-gnus" '("emacsvox-gnus-" "ems--" "gnus-summary-downcase-article"))


;;; Generated autoloads from emacsvox-gomoku.el

(register-definition-prefixes "emacsvox-gomoku" '("emacsvox-gomoku-" "ems--gomoku-" "gomoku-"))


;;; Generated autoloads from emacsvox-google.el

(autoload 'emacsvox-google-tts-speak "emacsvox-google" "\
Google Network TTS.
Optional interactive prefix arg `lang' specifies  language identifier
which becomes buffer-local.

(fn TEXT &optional LANG)" t)
(autoload 'emacsvox-google-tts-region "emacsvox-google" "\
Speak region using Google Network TTS.

(fn START END &optional ASK-LANG)" t)
(autoload 'emacsvox-google-tts-line "emacsvox-google" "\
TTS line using network TTS.
Use default voice for buffer.

(fn &optional LANG)" t)
(autoload 'emacsvox-google-tts-next-line "emacsvox-google" "\
TTS next line using network TTS.
Use default voice for buffer." t)
(autoload 'emacsvox-google-tts-previous-line "emacsvox-google" "\
TTS previous line using network TTS.
Use default voice for buffer." t)
(autoload 'emacsvox-google-search-after "emacsvox-google" "\
Google from calendar --- add after:date-at-point." t)
(autoload 'emacsvox-google-search-before "emacsvox-google" "\
Google from calendar --- add before:date-at-point." t)
(register-definition-prefixes "emacsvox-google" '("emacsvox-google-" "ems--gmaps-"))


;;; Generated autoloads from emacsvox-gridtext.el

(define-prefix-command 'emacsvox-gridtext 'emacsvox-gridtext-keymap)
(register-definition-prefixes "emacsvox-gridtext" '("emacsvox-gridtext-"))


;;; Generated autoloads from emacsvox-gtags.el

(register-definition-prefixes "emacsvox-gtags" '("ems--gtags-"))


;;; Generated autoloads from emacsvox-gud.el

(register-definition-prefixes "emacsvox-gud" '("ems--gud-display-line-after"))


;;; Generated autoloads from emacsvox-haskell.el

(register-definition-prefixes "emacsvox-haskell" '("ems--haskell-cabal-mode-after"))


;;; Generated autoloads from emacsvox-helm.el

(register-definition-prefixes "emacsvox-helm" '("emacsvox-helm-" "ems--helm-"))


;;; Generated autoloads from emacsvox-hide.el

(autoload 'emacsvox-hide-all-blocks-in-buffer "emacsvox-hide" "\
Hide all blocks.")
(autoload 'emacsvox-hide-or-expose-block "emacsvox-hide" "\
Hide or expose a block of text.
 Optional interactive prefix arg causes all blocks in current
buffer to be hidden or exposed.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-hide-or-expose-all-blocks "emacsvox-hide" "\
Hide or expose all blocks." t)
(register-definition-prefixes "emacsvox-hide" '("emacsvox-hid"))


;;; Generated autoloads from emacsvox-hideshow.el

(register-definition-prefixes "emacsvox-hideshow" '("ems--hs-"))


;;; Generated autoloads from emacsvox-hydra.el

(register-definition-prefixes "emacsvox-hydra" '("emacsvox-hydra-" "ems--lv-"))


;;; Generated autoloads from emacsvox-ibuffer.el

(register-definition-prefixes "emacsvox-ibuffer" '("emacsvox-ibuffer-s" "ems--ibuffer-"))


;;; Generated autoloads from emacsvox-ido.el

(register-definition-prefixes "emacsvox-ido" '("emacsvox-ido-" "ems--ido-"))


;;; Generated autoloads from emacsvox-iedit.el

(register-definition-prefixes "emacsvox-iedit" '("ems--iedit-"))


;;; Generated autoloads from emacsvox-indium.el

(register-definition-prefixes "emacsvox-indium" '("ems--indium-"))


;;; Generated autoloads from emacsvox-info.el

(autoload 'emacsvox-info-wizard "emacsvox-info" "\
Read a node spec from the minibuffer and launch
Info-goto-node.
See documentation for command `Info-goto-node' for details on
node-spec.

(fn NODE-SPEC)" t)
(register-definition-prefixes "emacsvox-info" '("emacsvox-info-" "ems--Info-"))


;;; Generated autoloads from emacsvox-ispell.el

(register-definition-prefixes "emacsvox-ispell" '("emacsvox-ispell-max-choices" "ems--ispell-"))


;;; Generated autoloads from emacsvox-ivy.el

(register-definition-prefixes "emacsvox-ivy" '("emacsvox-ivy-speak-selection" "ems--ivy-"))


;;; Generated autoloads from emacsvox-jabber.el

(register-definition-prefixes "emacsvox-jabber" '("emacsvox-jabber-" "ems--jabber-"))


;;; Generated autoloads from emacsvox-jdee.el

(register-definition-prefixes "emacsvox-jdee" '("ems--"))


;;; Generated autoloads from emacsvox-journalctl.el

(register-definition-prefixes "emacsvox-journalctl" '("ems--journalctl-quit-after"))


;;; Generated autoloads from emacsvox-js2.el

(register-definition-prefixes "emacsvox-js2" '("emacsvox-js2-hook" "ems--js2-"))


;;; Generated autoloads from emacsvox-keymap.el

(register-definition-prefixes "emacsvox-keymap" '("emacsvox-"))


;;; Generated autoloads from emacsvox-kmacro.el

(register-definition-prefixes "emacsvox-kmacro" '("ems--"))


;;; Generated autoloads from emacsvox-librivox.el

(autoload 'emacsvox-librivox "emacsvox-librivox" "\
Launch a Librivox Search.

(fn SEARCH-TYPE)" t)
(register-definition-prefixes "emacsvox-librivox" '("emacsvox-librivox-"))


;;; Generated autoloads from emacsvox-lispy.el

(register-definition-prefixes "emacsvox-lispy" '("emacsvox-lispy-setup" "ems--lispy-"))


;;; Generated autoloads from emacsvox-lua.el

(register-definition-prefixes "emacsvox-lua" '("ems--lua-"))


;;; Generated autoloads from emacsvox-m-player.el

(autoload 'emacsvox-m-player-add-dynamic "emacsvox-m-player" "\
Add file to the current  dynamic playlist.

(fn FILE)" t)
(defvar emacsvox-media-location-bindings nil "\
Map  keys  to launch MPlayer on a  directory.")
(custom-autoload 'emacsvox-media-location-bindings "emacsvox-m-player" nil)
(autoload 'emacsvox-multimedia "emacsvox-m-player" "\
Start or control Emacsvox multimedia player.
Controls media playback when already playing.

\\{emacsvox-m-player-mode-map}" t)
(autoload 'emacsvox-m-player-url "emacsvox-m-player" "\
Call emacsvox-m-player on  URL.
URL fragment specifies optional start position.

(fn URL &optional PLAYLIST-P)" t)
(autoload 'emacsvox-m-player "emacsvox-m-player" "\
Play  resource, or play dynamic playlist if set.  Optional prefix argument
play-list interprets resource as a play-list.  Second interactive
prefix arg adds option -allow-dangerous-playlist-parsing to mplayer.
See command \\[emacsvox-m-player-add-dynamic] for adding to the
dynamic playlist. 

(fn RESOURCE &optional PLAY-LIST)" t)
(autoload 'emacsvox-m-player-shuffle "emacsvox-m-player" "\
M-Player with shuffle turned on." t)
(defvar emacsvox-m-player-media-history nil "\
Record media urls we played.")
(autoload 'emacsvox-m-player-from-history "emacsvox-m-player" "\
Play media from the front of media-history.
   Interactive prefix arg invokes media history browser.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-m-player-play-rss "emacsvox-m-player" "\
Play an RSS stream.

(fn RSS-URL)" t)
(autoload 'emacsvox-m-player-locate-media "emacsvox-m-player" "\
Locate media matching  pattern.  The results can be
played as a play-list by pressing [RET] on the first line, see
 \\[emacsvox-dired-open-this-file] locally bound to C-RET
to play  tracks.

(fn PATTERN)" t)
(register-definition-prefixes "emacsvox-m-player" '("clip-" "emacsvox-" "ems-"))


;;; Generated autoloads from emacsvox-magit.el

(register-definition-prefixes "emacsvox-magit" '("emacsvox-magit-blame-speak" "ems--"))


;;; Generated autoloads from emacsvox-make-mode.el

(register-definition-prefixes "emacsvox-make-mode" '("ems--makefile-"))


;;; Generated autoloads from emacsvox-man.el

(register-definition-prefixes "emacsvox-man" '("emacsvox-man-" "ems--"))


;;; Generated autoloads from emacsvox-maths.el

(autoload 'emacsvox-maths-start "emacsvox-maths" "\
Start Maths server bridge." t)
(autoload 'emacsvox-maths-enter-guess "emacsvox-maths" "\
Send the guessed  LaTeX expression to Maths server. " t)
(autoload 'emacsvox-maths-enter "emacsvox-maths" "\
Send a LaTeX expression to Maths server,
 guess  based on context. 

(fn LATEX)" t)
(register-definition-prefixes "emacsvox-maths" '("emacsvox-maths" "ems--preview-at-point-after"))


;;; Generated autoloads from emacsvox-message.el

(register-definition-prefixes "emacsvox-message" '("ems--message-"))


;;; Generated autoloads from emacsvox-metapost.el

(register-definition-prefixes "emacsvox-metapost" '("ems--meta-"))


;;; Generated autoloads from emacsvox-midge.el

(register-definition-prefixes "emacsvox-midge" '("ems--midge-" "midge-mode-hook"))


;;; Generated autoloads from emacsvox-mines.el

(register-definition-prefixes "emacsvox-mines" '("emacsvox-mines-" "ems--mines-"))


;;; Generated autoloads from emacsvox-mspools.el

(register-definition-prefixes "emacsvox-mspools" '("ems--mspools-" "mspools-"))


;;; Generated autoloads from emacsvox-muggles.el

(register-definition-prefixes "emacsvox-muggles" '("emacsvox-muggles-"))


;;; Generated autoloads from emacsvox-newsticker.el

(register-definition-prefixes "emacsvox-newsticker" '("emacsvox-newsticker-summarize-item" "ems--newsticker-"))


;;; Generated autoloads from emacsvox-nm.el

(register-definition-prefixes "emacsvox-nm" '("nm-"))


;;; Generated autoloads from emacsvox-notmuch.el

(register-definition-prefixes "emacsvox-notmuch" '("ems--notmuch-"))


;;; Generated autoloads from emacsvox-nov.el

(register-definition-prefixes "emacsvox-nov" '("emacsvox-nov-mode-hook"))


;;; Generated autoloads from emacsvox-nxml.el

(register-definition-prefixes "emacsvox-nxml" '("emacsvox-nxml-summarize-outline" "ems--nxml-"))


;;; Generated autoloads from emacsvox-ocr.el

(autoload 'emacsvox-ocr "emacsvox-ocr" "\
An OCR front-end for the Emacsvox desktop.  

Page image is acquired using tools from the SANE package.
The acquired image is run through the OCR engine if one is
available, and the results placed in a buffer that is
suitable for browsing the results.

For detailed help, invoke command emacsvox-ocr bound to
\\[emacsvox-ocr] to launch emacsvox-ocr-mode, and press
`?' to display mode-specific help for emacsvox-ocr-mode." t)
(register-definition-prefixes "emacsvox-ocr" '("emacsvox-ocr-"))


;;; Generated autoloads from emacsvox-org.el

(autoload 'emacsvox-org-capture-link "emacsvox-org" "\
Capture hyperlink to current context.
To use this command, first do `customize-variable'
`org-capture-template' and assign letter `h' to a template that
creates the hyperlink on capture.  Optional interactive prefix
arg just opens the file

(fn &optional OPEN)" t)
(register-definition-prefixes "emacsvox-org" '("emacsvox-org-" "ems--" "org-" "tvr-org-"))


;;; Generated autoloads from emacsvox-outline.el

(register-definition-prefixes "emacsvox-outline" '("emacsvox-outline-" "ems--outline-"))


;;; Generated autoloads from emacsvox-package.el

(register-definition-prefixes "emacsvox-package" '("emacsvox-package-" "ems--package-menu-"))


;;; Generated autoloads from emacsvox-paradox.el

(register-definition-prefixes "emacsvox-paradox" '("emacsvox-paradox-" "ems--"))


;;; Generated autoloads from emacsvox-perl.el

(register-definition-prefixes "emacsvox-perl" '("ems--"))


;;; Generated autoloads from emacsvox-pianobar.el

(autoload 'emacsvox-pianobar "emacsvox-pianobar" "\
Start or control Emacsvox Pianobar player." t)
(register-definition-prefixes "emacsvox-pianobar" '("emacsvox-pianobar-" "ems--pianobar-"))


;;; Generated autoloads from emacsvox-pipewire.el

(register-definition-prefixes "emacsvox-pipewire" '("ems--pipewire-after"))


;;; Generated autoloads from emacsvox-popup.el

(register-definition-prefixes "emacsvox-popup" '("emacsvox-popup-speak-item" "ems--popup-menu-"))


;;; Generated autoloads from emacsvox-preamble.el

(register-definition-prefixes "emacsvox-preamble" '("emacsvox-" "ems-" "sox-"))


;;; Generated autoloads from emacsvox-proced.el

(register-definition-prefixes "emacsvox-proced" '("emacsvox-proced-" "ems--proced-"))


;;; Generated autoloads from emacsvox-projectile.el

(register-definition-prefixes "emacsvox-projectile" '("emacsvox-projectile-file-action" "ems--projectile-"))


;;; Generated autoloads from emacsvox-pronounce.el

(register-definition-prefixes "emacsvox-pronounce" '("emacsvox-" "ems-"))


;;; Generated autoloads from emacsvox-py.el

(register-definition-prefixes "emacsvox-py" '("ems--py"))


;;; Generated autoloads from emacsvox-pydoc.el

(register-definition-prefixes "emacsvox-pydoc" '("ems--pydoc-after"))


;;; Generated autoloads from emacsvox-python.el

(register-definition-prefixes "emacsvox-python" '("ems--python-"))


;;; Generated autoloads from emacsvox-racer.el

(register-definition-prefixes "emacsvox-racer" '("ems--racer-describe-after"))


;;; Generated autoloads from emacsvox-racket.el

(register-definition-prefixes "emacsvox-racket" '("ems--racket-describe-after"))


;;; Generated autoloads from emacsvox-re-builder.el

(register-definition-prefixes "emacsvox-re-builder" '("ems--re"))


;;; Generated autoloads from emacsvox-reftex.el

(register-definition-prefixes "emacsvox-reftex" '("ems--reftex-"))


;;; Generated autoloads from emacsvox-rmail.el

(register-definition-prefixes "emacsvox-rmail" '("emacsvox-rmail-s" "ems--rmail-"))


;;; Generated autoloads from emacsvox-rpm-spec.el

(register-definition-prefixes "emacsvox-rpm-spec" '("emacsvox-rpm-spec-"))


;;; Generated autoloads from emacsvox-rst.el

(register-definition-prefixes "emacsvox-rst" '("ems--rst-"))


;;; Generated autoloads from emacsvox-ruby.el

(register-definition-prefixes "emacsvox-ruby" '("ems--ruby-"))


;;; Generated autoloads from emacsvox-rust-mode.el

(register-definition-prefixes "emacsvox-rust-mode" '("emacsvox-rust-mode-setup" "ems--rust-"))


;;; Generated autoloads from emacsvox-sage.el

(register-definition-prefixes "emacsvox-sage" '("emacsvox-sage-" "ems--sage-shell"))


;;; Generated autoloads from emacsvox-sdcv.el

(register-definition-prefixes "emacsvox-sdcv" '("emacsvox-sdcv-" "ems--sdcv-quit-after"))


;;; Generated autoloads from emacsvox-selectrum.el

(register-definition-prefixes "emacsvox-selectrum" '("ems--selectrum-"))


;;; Generated autoloads from emacsvox-ses.el

(register-definition-prefixes "emacsvox-ses" '("emacsvox-ses-" "ems--ses-"))


;;; Generated autoloads from emacsvox-sgml-mode.el

(register-definition-prefixes "emacsvox-sgml-mode" '("ems--sgml-"))


;;; Generated autoloads from emacsvox-sh-script.el

(register-definition-prefixes "emacsvox-sh-script" '("ems--sh-"))


;;; Generated autoloads from emacsvox-shx.el

(register-definition-prefixes "emacsvox-shx" '("ems--shx-" "shx-cmd-"))


;;; Generated autoloads from emacsvox-slime.el

(register-definition-prefixes "emacsvox-slime" '("ems--slime-"))


;;; Generated autoloads from emacsvox-smartparens.el

(register-definition-prefixes "emacsvox-smartparens" '("ems--sp-"))


;;; Generated autoloads from emacsvox-solitaire.el

(register-definition-prefixes "emacsvox-solitaire" '("emacsvox-solitaire-" "ems--solitaire-"))


;;; Generated autoloads from emacsvox-sounds.el

(register-definition-prefixes "emacsvox-sounds" '("emacsvox-" "ems--"))


;;; Generated autoloads from emacsvox-speak.el

(autoload 'emacsvox-filter-after "emacsvox-speak" "\
Add after:today filter" t)
(autoload 'emacsvox-filter-before "emacsvox-speak" "\
Add before:today filter" t)
(register-definition-prefixes "emacsvox-speak" '("describe-help-keys" "emacsvox-" "ems-"))


;;; Generated autoloads from emacsvox-speedbar.el

(register-definition-prefixes "emacsvox-speedbar" '("emacsvox-speedbar-" "ems--speedbar-"))


;;; Generated autoloads from emacsvox-sql.el

(register-definition-prefixes "emacsvox-sql" '("ems--sql"))


;;; Generated autoloads from emacsvox-sudoku.el

(register-definition-prefixes "emacsvox-sudoku" '("emacsvox-sudoku-" "ems--sudoku-"))


;;; Generated autoloads from emacsvox-supercite.el

(register-definition-prefixes "emacsvox-supercite" '("ems--sc-"))


;;; Generated autoloads from emacsvox-syslog.el

(register-definition-prefixes "emacsvox-syslog" '("emacsvox-syslog-setup" "ems--syslog-"))


;;; Generated autoloads from emacsvox-tab-bar.el

(register-definition-prefixes "emacsvox-tab-bar" '("emacsvox-tab-bar-speak-tab-name" "ems--tab-bar-"))


;;; Generated autoloads from emacsvox-table.el

(autoload 'emacsvox-table-make-table "emacsvox-table" "\
Construct a table object from elements.

(fn ELEMENTS)")
(register-definition-prefixes "emacsvox-table" '("emacsvox-table-"))


;;; Generated autoloads from emacsvox-table-ui.el

(autoload 'emacsvox-table-prepare-table-buffer "emacsvox-table-ui" "\
Prepare tabular data.

(fn TABLE BUFFER)")
(autoload 'emacsvox-table-find-file "emacsvox-table-ui" "\
Open a file containing table data and display it in table mode.
emacsvox table mode is designed to let you browse tabular data using
all the power of the two-dimensional spatial layout while giving you
sufficient contextual information.  The etc/tables subdirectory of the
emacsvox distribution contains some sample tables --these are the
CalTrain schedules.  Execute command `describe-mode' bound to
\\[describe-mode] in a buffer that is in emacsvox table mode to read
the documentation on the table browser.

(fn FILENAME)" t)
(autoload 'emacsvox-table-find-csv-file "emacsvox-table-ui" "\
Process a csv (comma separated values) file.
The processed  data is presented using emacsvox table navigation. 

(fn FILENAME)" t)
(autoload 'emacsvox-table-view-csv-buffer "emacsvox-table-ui" "\
Process a csv (comma separated values) data.
The processed  data is  presented using emacsvox table navigation. 

(fn &optional BUFFER-NAME)" t)
(autoload 'emacsvox-table-view-csv-url "emacsvox-table-ui" "\
Process a csv (comma separated values) data at  `URL'.
The processed  data is  presented using emacsvox table navigation. 

(fn URL &optional BUFFER-NAME)" t)
(register-definition-prefixes "emacsvox-table-ui" '("emacsvox-table-" "ems-csv-"))


;;; Generated autoloads from emacsvox-tabulate.el

(register-definition-prefixes "emacsvox-tabulate" '("ems-"))


;;; Generated autoloads from emacsvox-tabulated-list.el

(register-definition-prefixes "emacsvox-tabulated-list" '("emacsvox-tabulated-list-"))


;;; Generated autoloads from emacsvox-tar.el

(register-definition-prefixes "emacsvox-tar" '("emacsvox-tar-s" "ems--tar-"))


;;; Generated autoloads from emacsvox-tcl.el

(register-definition-prefixes "emacsvox-tcl" '("ems--" "tcl-"))


;;; Generated autoloads from emacsvox-tempo.el

(register-definition-prefixes "emacsvox-tempo" '("ems--"))


;;; Generated autoloads from emacsvox-tetris.el

(register-definition-prefixes "emacsvox-tetris" '("emacsvox-tetris-" "ems--tetris-" "tetris-"))


;;; Generated autoloads from emacsvox-texinfo.el

(register-definition-prefixes "emacsvox-texinfo" '("emacsvox-texinfo-mode-hook" "ems--"))


;;; Generated autoloads from emacsvox-threes.el

(register-definition-prefixes "emacsvox-threes" '("emacsvox-threes-" "ems--threes-"))


;;; Generated autoloads from emacsvox-tide.el

(register-definition-prefixes "emacsvox-tide" '("ems--tide-"))


;;; Generated autoloads from emacsvox-todo-mode.el

(register-definition-prefixes "emacsvox-todo-mode" '("ems--todo-"))


;;; Generated autoloads from emacsvox-transient.el

(register-definition-prefixes "emacsvox-transient" '("emacsvox-transient-" "ems--transient-"))


;;; Generated autoloads from emacsvox-treesit.el

(register-definition-prefixes "emacsvox-treesit" '("emacsvox-treesit-inspect"))


;;; Generated autoloads from emacsvox-url-template.el

(autoload 'emacsvox-url-template-get "emacsvox-url-template" "\
Lookup key and return corresponding template. 

(fn KEY)")
(defvar emacsvox-stock-tickers (list "goog" "aapl" "meta" "amzn" "nflx" "msft" "nvda") "\
Set this to the stock tickers you want to check. Default is
the current fab-7!. Tickers is a list of stock symbols sorted in lexical order
with duplicates removed when saving as a list of string.")
(custom-autoload 'emacsvox-stock-tickers "emacsvox-url-template" nil)
(autoload 'emacsvox-url-template-open "emacsvox-url-template" "\
Fetch resource identified by URL template.

(fn UT)")
(autoload 'emacsvox-url-template-fetch "emacsvox-url-template" "\
Fetch a pre-defined resource.
Use Emacs completion to obtain a list of available resources.
Resources typically prompt for the relevant information
before completing the request.
Optional interactive prefix arg displays documentation for specified resource.

(fn &optional DOCUMENTATION)" t)
(register-definition-prefixes "emacsvox-url-template" '("emacsvox-" "ems--ut-quotes-cleanup"))


;;; Generated autoloads from emacsvox-vdiff.el

(register-definition-prefixes "emacsvox-vdiff" '("emacsvox-vdiff-" "ems--vdiff-"))


;;; Generated autoloads from emacsvox-vertico.el

(register-definition-prefixes "emacsvox-vertico" '("emacsvox-vertico--prev-" "ems--vertico-"))


;;; Generated autoloads from emacsvox-view.el

(register-definition-prefixes "emacsvox-view" '("ems--"))


;;; Generated autoloads from emacsvox-vm.el

(register-definition-prefixes "emacsvox-vm" '("emacsvox-" "ems--vm-" "vm-"))


;;; Generated autoloads from emacsvox-vterm.el

(register-definition-prefixes "emacsvox-vterm" '("emacsvox-vterm-" "ems--vterm-"))


;;; Generated autoloads from emacsvox-vuiet.el

(register-definition-prefixes "emacsvox-vuiet" '("emacsvox-vuiet-track-info" "ems--vuiet-"))


;;; Generated autoloads from emacsvox-wdired.el

(register-definition-prefixes "emacsvox-wdired" '("ems--wdired-"))


;;; Generated autoloads from emacsvox-we.el

(register-definition-prefixes "emacsvox-we" '("emacsvox-we-"))


;;; Generated autoloads from emacsvox-websearch.el

(define-prefix-command 'emacsvox-websearch)
(register-definition-prefixes "emacsvox-websearch" '("emacsvox-websearch-" "ems--"))


;;; Generated autoloads from emacsvox-webspace.el

(define-prefix-command 'emacsvox-webspace 'emacsvox-webspace-keymap)
(autoload 'emacsvox-webspace-headlines "emacsvox-webspace" "\
Startup Headlines ticker using RSS/Atom  feeds." t)
(autoload 'emacsvox-webspace-feed-reader "emacsvox-webspace" "\
Display Feed Reader Feed list in a WebSpace buffer.
Optional interactive prefix arg forces a refresh.

(fn &optional REFRESH)" t)
(register-definition-prefixes "emacsvox-webspace" '("emacsvox-webspace-"))


;;; Generated autoloads from emacsvox-widget.el

(register-definition-prefixes "emacsvox-widget" '("emacsvox-widget-" "ems--widget-"))


;;; Generated autoloads from emacsvox-winring.el

(register-definition-prefixes "emacsvox-winring" '("ems--winring-"))


;;; Generated autoloads from emacsvox-wizards.el

(autoload 'emacsvox-view-emacsvox-news "emacsvox-wizards" "\
Display emacsvox News for a given version." t)
(autoload 'emacsvox-speak-popup-messages "emacsvox-wizards" "\
Pop up Messages  and switch to it." t)
(autoload 'emacsvox-speak-telephone-directory "emacsvox-wizards" "\
Lookup and display a phone number.
With prefix arg, opens the phone book for editing.

(fn &optional EDIT)" t)
(autoload 'emacsvox-wizards-find-file-as-root "emacsvox-wizards" "\
Automatically edit file with root-privileges (using
tramp/sudo), if the file is not writable by user.

(fn FILE)" t)
(autoload 'emacsvox-learn-emacs "emacsvox-wizards" "\
Helps you learn the keys.  You can press keys and hear what they do.
To leave, press \\[keyboard-quit]." t)
(autoload 'emacsvox-speak-this-buffer-other-window-display "emacsvox-wizards" "\
Speak this buffer as displayed in a different frame or window.  Emacs
allows you to display the same buffer in multiple windows or
frames.  These different windows can display different
portions of the buffer.  This is equivalent to leaving a
book open at places at once.  This command allows you to
listen to the places where you have left the book open.  

(fn WINDOW)" t)
(autoload 'emacsvox-speak-this-buffer-previous-display "emacsvox-wizards" "\
Speak this buffer as displayed in a `previous' window.
See documentation for command
`emacsvox-speak-this-buffer-other-window-display' for the
meaning of `previous'." t)
(autoload 'emacsvox-speak-this-buffer-next-display "emacsvox-wizards" "\
Speak this buffer as displayed in a `previous' window.
See documentation for command
`emacsvox-speak-this-buffer-other-window-display' for the
meaning of `next'." t)
(autoload 'emacsvox-select-this-buffer-previous-display "emacsvox-wizards" "\
Select this buffer as displayed in a `previous' window.
See documentation for command
`emacsvox-select-this-buffer-other-window-display' for the
meaning of `previous'." t)
(autoload 'emacsvox-select-this-buffer-next-display "emacsvox-wizards" "\
Select this buffer as displayed in a `next' frame.
See documentation for command
`emacsvox-select-this-buffer-other-window-display' for the
meaning of `next'." t)
(autoload 'emacsvox-show-style-at-point "emacsvox-wizards" "\
Show value of property personality (and possibly face) at point." t)
(autoload 'emacsvox-show-property-at-point "emacsvox-wizards" "\
Show value of PROPERTY at point.
If optional arg property is not supplied, read it interactively. 

(fn &optional PROPERTY)" t)
(autoload 'emacsvox-skip-blank-lines-forward "emacsvox-wizards" "\
Move forward across blank lines, then speak line.
" t)
(autoload 'emacsvox-skip-blank-lines-backward "emacsvox-wizards" "\
Move backward  across blank lines, then speak line. " t)
(autoload 'emacsvox-skip-space-forwar "emacsvox-wizards" "\
Skip forward across blanks." t)
(autoload 'emacsvox-skip-space-backward "emacsvox-wizards" "\
Skip back across blanks." t)
(autoload 'emacsvox-wizards-shell-toggle "emacsvox-wizards" "\
Switch to  shell  and cd to
  directory of the previously current buffer." t)
(autoload 'emacsvox-wizards-tramp-open-location "emacsvox-wizards" "\
Open specified tramp location.
Location is specified by name.

(fn NAME)" t)
(autoload 'emacsvox-customize "emacsvox-wizards" "\
Customize Emacsvox." t)
(autoload 'emacsvox-wizards-squeeze-blanks "emacsvox-wizards" "\
Squeeze multiple blank lines.

(fn START END)" t)
(autoload 'emacsvox-wizards-how-many-matches "emacsvox-wizards" "\
If you define a file local variable
called `emacsvox-occur-pattern' that holds a regular expression
that matches  lines of interest, you can use this command to
run `how-many' to count  matching header lines.
With interactive prefix arg, prompts for and remembers the file local pattern.

(fn START END &optional PREFIX)" t)
(autoload 'emacsvox-wizards-occur-header-lines "emacsvox-wizards" "\
If you define a file local variable called
`emacsvox-occur-pattern' that holds a regular expression that
matches header lines, you can use this command to
run `occur' to find matching header lines. With prefix arg,
prompts for and sets value of the file local pattern.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-kill-buffer-quietly "emacsvox-wizards" "\
Kill current buffer without  confirmation." t)
(autoload 'emacsvox-wizards-vc-viewer "emacsvox-wizards" "\
View contents of  virtual console.

(fn CONSOLE)" t)
(autoload 'emacsvox-wizards-find-longest-line-in-region "emacsvox-wizards" "\
Find longest line in region and move to it. 

(fn START END)" t)
(autoload 'emacsvox-wizards-find-longest-paragraph-in-region "emacsvox-wizards" "\
Find longest paragraph in region, and move to it. 

(fn START END)" t)
(autoload 'emacsvox-wizards-show-face "emacsvox-wizards" "\
Show  properties of  face.

(fn FACE)" t)
(autoload 'emacsvox-wizards-speak-iso-datetime "emacsvox-wizards" "\
Speak ISO date-time.

(fn ISO)" t)
(autoload 'emacsvox-wizards-toggle-mm-dd-yyyy-date-pronouncer "emacsvox-wizards" "\
Toggle pronunciation of mm-dd-yyyy dates." t)
(autoload 'emacsvox-wizards-toggle-yyyymmdd-date-pronouncer "emacsvox-wizards" "\
Toggle pronunciation of yyyymmdd  dates." t)
(autoload 'emacsvox-wizards-units "emacsvox-wizards" "\
Run units." t)
(autoload 'emacsvox-wizards-shell "emacsvox-wizards" "\
Run Emacs  `shell' command when not in a shell buffer, or
when called with a prefix argument. When called from a shell buffer,
switches to `next' shell buffer. When called from outside a shell
buffer, find the most `appropriate shell' and switch to it. Once
switched, set default directory in that target shell to the directory
of the source buffer.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-wizards-shell-by-key "emacsvox-wizards" "\
Switch to shell buffer by key. This provides a predictable
  means for switching to a specific shell buffer. When invoked
  from a non-shell-mode buffer that is a dired-buffer or is
  visiting a file, invokes `cd ' in the shell to change to the.
  value of `default-directory' When already in a shell buffer,
  interactive prefix arg `prefix' causes this shell to be
  re-keyed if appropriate --- see
  \\[emacsvox-wizards-shell-re-key] for an explanation of how
  re-keying works.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-wizards-project-shells-initialize "emacsvox-wizards" "\
Create shells per `emacsvox-wizards-project-shells'.")
(autoload 'emacsvox-wizards-shell-directory-reset "emacsvox-wizards" "\
Set current directory to this shell's initial directory if one was
defined.  If not in a shell buffer, switch to our Home shell buffer.
With interactive prefix-arg, change this shell's  project directory to
the current directory.

(fn &optional PREFIX)" t)
(autoload 'emacsvox-wizards-espeak-string "emacsvox-wizards" "\
Speak string in lang via ESpeak.
Lang is obtained from property `lang' on string, or via an
interactive prompt.

(fn STRING)" t)
(autoload 'emacsvox-wizards-espeak-region "emacsvox-wizards" "\
Speak region using ESpeak polyglot wizard.

(fn START END)" t)
(autoload 'emacsvox-wizards-espeak-line "emacsvox-wizards" "\
Speak line using espeak polyglot wizard." t)
(autoload 'emacsvox-wizards-show-eval-result "emacsvox-wizards" "\
Pretty-print and view Lisp evaluation results.

(fn FORM)" t)
(autoload 'emacsvox-wizards-enumerate-matching-commands "emacsvox-wizards" "\
Return list of commands whose names match pattern.

(fn PATTERN)" t)
(autoload 'emacsvox-wizards-enumerate-uncovered-commands "emacsvox-wizards" "\
Enumerate unadvised commands matching pattern.
Optional interactive prefix arg `bound'
filters out commands that dont have an active key-binding.

(fn PATTERN &optional BOUND)" t)
(autoload 'emacsvox-wizards-module-enumerate-uncovered-commands "emacsvox-wizards" "\
Enumerate uncovered commands from module m

(fn M)" t)
(autoload 'emacsvox-wizards-enumerate-unmapped-faces "emacsvox-wizards" "\
Enumerate unmapped faces matching pattern.

(fn &optional PATTERN)" t)
(autoload 'emacsvox-wizards-enumerate-matching-faces "emacsvox-wizards" "\
Enumerate  faces matching pattern.

(fn PATTERN)" t)
(autoload 'emacsvox-wizards-shell-command-on-current-file "emacsvox-wizards" "\
Prompts for and runs shell command on current file.

(fn COMMAND)" t)
(autoload 'emacsvox-wizards-view-buffers-filtered-by-this-mode "emacsvox-wizards" "\
Buffer menu filtered by  mode of current-buffer." t)
(autoload 'emacsvox-wizards-view-buffers-filtered-by-m-player-mode "emacsvox-wizards" "\
Buffer menu filtered by  m-player mode." t)
(autoload 'emacsvox-wizards-eww-buffer-list "emacsvox-wizards" "\
Display list of  EWW buffers." t)
(autoload 'emacsvox-wizards-tune-in-radio-browse "emacsvox-wizards" "\
Browse Tune-In Radio.
Optional interactive prefix arg `category' prompts for a category.

(fn &optional CATEGORY)" t)
(autoload 'emacsvox-wizards-tune-in-radio-search "emacsvox-wizards" "\
Search Tune-In Radio." t)
(autoload 'emacsvox-wizards-set-colors "emacsvox-wizards" "\
Prompt for foreground and background colors." t)
(autoload 'emacsvox-wizards-color-diff-at-point "emacsvox-wizards" "\
Speak difference between background and foreground color at point.
With interactive prefix arg, set foreground and background color first.

(fn &optional SET)" t)
(autoload 'emacsvox-wizards-colors "emacsvox-wizards" "\
Display list of colors and setup a callback to activate color
under point as either the foreground or background color." t)
(autoload 'emacsvox-wizards-color-at-point "emacsvox-wizards" "\
Echo foreground/background color at point." t)
(autoload 'emacsvox-wizards-color-wheel "emacsvox-wizards" "\
Manipulate a simple color wheel and display the name and shade
  of the resulting color.  Prompts for a color from which to
  start exploration.

Keyboard Commands During Interaction:
Up/Down: Increase/Decrement along current axis using specified step-size.
=: Set value on current axis to number read from minibuffer.
Left/Right: Switch color axis along which to move.
b/f: Quit  wheel after setting background/foreground color to current value.
n: Read color name from minibuffer.
c: Complement  current color.
s: Set stepsize to number read from minibuffer.
q: Quit color wheel, after copying current hex value to kill-ring.

(fn START)" t)
(autoload 'emacsvox-wizards-swap-fg-and-bg "emacsvox-wizards" "\
Swap foreground and background." t)
(autoload 'emacsvox-wizards-show-theme "emacsvox-wizards" "\
Display colors in  palette.
Prompts for a color palette variable as used in the modus theme and
  its variants,
and pops to a buffer that describes the colors used in that palette.

(fn PALETTE)" t)
(autoload 'emacsvox-wizards-noaa-weather "emacsvox-wizards" "\
Display weather  using NOAA Weather API.
Address is a string and can include house-number, street name,
city and zip.  Data is retrieved only once, subsequent calls
switch to previously displayed results. Kill that buffer or use
an interactive prefix arg (C-u) to get new data.  Optional second
interactive prefix arg (C-u C-u) asks for location address;
Default is to display weather for `gmaps-my-address'.

(fn &optional ASK)" t)
(autoload 'emacsvox-wizards-google-news "emacsvox-wizards" "\
Clean up news.google.com." t)
(autoload 'emacsvox-wizards-execute-asynchronously "emacsvox-wizards" "\
Read key-sequence, then execute its command on a new thread.

(fn KEY)" t)
(autoload 'emacsvox-wizards-describe-voice "emacsvox-wizards" "\
Describe  voice --- analogous to \\[describe-face].
When called interactively, `personality' defaults to first
personality at point. 

(fn PERSONALITY)" t)
(autoload 'emacsvox-wizards-end-of-word "emacsvox-wizards" "\
move to end of word

(fn ARG)" t)
(autoload 'emacsvox-wizards-comma-at-end-of-word "emacsvox-wizards" "\
Move to the end of current word and add a comma." t)
(autoload 'emacsvox-wizards-lacheck-buffer-file "emacsvox-wizards" "\
Run Lacheck on current buffer." t)
(autoload 'emacsvox-wizards-tex-tie-current-word "emacsvox-wizards" "\
Tie the next n  words.

(fn N)" t)
(autoload 'emacsvox-wizards-snarf-sexp "emacsvox-wizards" "\
Snarf the contents between delimiters at point.
Optional interactive prefix arg deletes it.

(fn &optional DELETE)" t)
(autoload 'emacsvox-wizards-portfolio "emacsvox-wizards" "\
View stock quotes" t)
(register-definition-prefixes "emacsvox-wizards" '("emacsvox-" "ems-"))


;;; Generated autoloads from emacsvox-woman.el

(register-definition-prefixes "emacsvox-woman" '("ems--WoMan-"))


;;; Generated autoloads from emacsvox-xkcd.el

(register-definition-prefixes "emacsvox-xkcd" '("emacsvox-xkcd-" "ems--" "xkcd-transcript"))


;;; Generated autoloads from emacsvox-xref.el

(register-definition-prefixes "emacsvox-xref" '("ems--xref-find-references-after"))


;;; Generated autoloads from emacsvox-xslt.el

(autoload 'emacsvox-xslt-region "emacsvox-xslt" "\
Apply XSLT transformation to region and replace it with the result.  

(fn XSL START END &optional PARAMS NO-COMMENT)")
(autoload 'emacsvox-xslt-url "emacsvox-xslt" "\
Apply XSLT transformation to url
and return the results in a newly created buffer. 

(fn XSL URL &optional PARAMS NO-COMMENT)")
(autoload 'emacsvox-xslt-xml-url "emacsvox-xslt" "\
Apply XSLT transformation to XML url
and return the results in a newly created buffer. 

(fn XSL URL &optional PARAMS)")
(autoload 'emacsvox-xslt-view-file "emacsvox-xslt" "\
Transform `file' using `style' and preview via browse-url.

(fn STYLE FILE)" t)
(autoload 'emacsvox-xslt-view-rss-file "emacsvox-xslt" "\
View RSS file.

(fn FILE)" t)
(autoload 'emacsvox-xslt-view-atom-file "emacsvox-xslt" "\
View Atom file.

(fn FILE)" t)
(autoload 'emacsvox-xslt-view "emacsvox-xslt" "\
Browse URL with specified XSL style.

(fn STYLE URL)" t)
(register-definition-prefixes "emacsvox-xslt" '("emacsvox-xslt-"))


;;; Generated autoloads from emacsvox-yaml.el

(register-definition-prefixes "emacsvox-yaml" '("ems--yaml-"))


;;; Generated autoloads from emacsvox-yasnippet.el

(register-definition-prefixes "emacsvox-yasnippet" '("ems--yas-insert-snippet-after"))


;;; Generated autoloads from espeak-voices.el

(autoload 'espeak "espeak-voices" "\
Start ESpeak." t)
(autoload 'espeak-configure-tts "espeak-voices" "\
Configure  to use eSpeak.")
(register-definition-prefixes "espeak-voices" '("espeak-" "tts-default-voice"))


;;; Generated autoloads from extra-muggles.el

(register-definition-prefixes "extra-muggles" '("emacsvox-muggles-"))


;;; Generated autoloads from g-utils.el

(register-definition-prefixes "g-utils" '("g-"))


;;; Generated autoloads from gm-nnir.el

(autoload 'gm-nnir-group-make-gmail-group "gm-nnir" "\
Use GMail search syntax exclusively.
See https://support.google.com/mail/answer/7190?hl=en for syntax.
 note: nnimap-address etc are available as local vars if needed
 in these functions.

(fn QUERY)" t)
(register-definition-prefixes "gm-nnir" '("gm-nnir-"))


;;; Generated autoloads from gmaps.el

(autoload 'gmaps-address-geocode "gmaps" "\
Return lat/long for a given address.

(fn ADDRESS)")
(defvar gmaps-my-address nil "\
Location address. Setting this updates gmaps-my-location
coordinates via geocoding.")
(custom-autoload 'gmaps-my-address "gmaps" nil)
(autoload 'gmaps "gmaps" "\
Google Maps Interaction." t)
(register-definition-prefixes "gmaps" '("gmaps-"))


;;; Generated autoloads from gweb.el

(register-definition-prefixes "gweb" '("gweb-"))


;;; Generated autoloads from ladspa.el

(defconst ladspa-home (or (getenv "LADSPA_PATH") "/usr/lib/ladspa") "\
Installation location for Ladspa plugins.")
(autoload 'ladspa "ladspa" "\
Ladspa workbench.

(fn &optional REFRESH)" t)
(register-definition-prefixes "ladspa" '("ladspa-"))


;;; Generated autoloads from light.el

(autoload 'light-get "light" "\
Get  brightness level." t)
(autoload 'light-set "light" "\
Set brightness.

(fn BRIGHTNESS)" t)
(autoload 'light-increment "light" "\
Increase brightness." t)
(autoload 'light-decrement "light" "\
Decrease brightness." t)
(autoload 'light-black "light" "\
Black screen." t)
(autoload 'light-white "light" "\
White screen." t)
(register-definition-prefixes "light" '("light-"))


;;; Generated autoloads from mac-voices.el

(autoload 'mac "mac-voices" "\
Mac TTS." t)
(autoload 'mac-configure-tts "mac-voices" "\
Configure TTS  to use mac.")
(register-definition-prefixes "mac-voices" '("mac-"))


;;; Generated autoloads from omaps.el

(register-definition-prefixes "omaps" '("omaps-"))


;;; Generated autoloads from outloud-voices.el

(autoload 'outloud "outloud-voices" "\
Start Outloud." t)
(autoload 'outloud-configure-tts "outloud-voices" "\
Configure TTS  to use Outloud.")
(register-definition-prefixes "outloud-voices" '("outloud-"))


;;; Generated autoloads from pip.el

(autoload 'pip-speak "pip" "\
Speak text

(fn TEXT)" t)
(register-definition-prefixes "pip" '("pip-"))


;;; Generated autoloads from plain-voices.el

(autoload 'plain "plain-voices" "\
Plain TTS." t)
(autoload 'plain-configure-tts "plain-voices" "\
Configures TTS  to use Plain.")
(register-definition-prefixes "plain-voices" '("plain-"))


;;; Generated autoloads from soundscape.el

(autoload 'soundscape "soundscape" "\
Play soundscape.

(fn SCAPE)" t)
(autoload 'soundscape-toggle "soundscape" "\
Toggle automatic SoundScapes.
Run command \\[soundscape-theme] to see the default mode->mood mapping." t)
(register-definition-prefixes "soundscape" '("soundscape-"))


;;; Generated autoloads from sox.el

(autoload 'sox "sox" "\
Create a new Audio Workbench or switch to one." t)
(autoload 'sox-play "sox" "\
Play sound ." t)
(register-definition-prefixes "sox" '("ems--sox-" "sox-"))


;;; Generated autoloads from sox-gen.el

(register-definition-prefixes "sox-gen" '("sox-"))


;;; Generated autoloads from swiftmac-voices.el

(autoload 'swiftmac "swiftmac-voices" "\
SwiftMac TTS." t)
(autoload 'swiftmac-configure-tts "swiftmac-voices" "\
Configure TTS  to use swiftmac.")
(register-definition-prefixes "swiftmac-voices" '("swiftmac-"))


;;; Generated autoloads from tetris.el

(autoload 'tetris "tetris" "\
Play the Tetris game.
Shapes drop from the top of the screen, and the user has to move and
rotate the shape to fit in with those at the bottom of the screen so
as to form complete rows.

tetris-mode keybindings:
   \\<tetris-mode-map>
\\[tetris-start-game]   Starts a new game of Tetris
\\[tetris-end-game]     Terminates the current game
\\[tetris-pause-game]   Pauses (or resumes) the current game
\\[tetris-move-left]    Moves the shape one square to the left
\\[tetris-move-right]   Moves the shape one square to the right
\\[tetris-rotate-prev]  Rotates the shape clockwise
\\[tetris-rotate-next]  Rotates the shape anticlockwise
\\[tetris-move-bottom]  Drops the shape to the bottom of the playing area

" t)
(register-definition-prefixes "tetris" '("tetris-"))


;;; Generated autoloads from voice-defs.el

(register-definition-prefixes "voice-defs" '("voice-"))


;;; Generated autoloads from voice-setup.el

(register-definition-prefixes "voice-setup" '("defvoice" "global-voice-lock-mode" "voice-"))


;;; Generated autoloads from xbacklight.el

(autoload 'xbacklight-get "xbacklight" "\
Get  brightness level." t)
(autoload 'xbacklight-set "xbacklight" "\
Set brightness.

(fn BRIGHTNESS)" t)
(autoload 'xbacklight-increment "xbacklight" "\
Increase brightness." t)
(autoload 'xbacklight-decrement "xbacklight" "\
Decrease brightness." t)
(autoload 'xbacklight-black "xbacklight" "\
Black screen." t)
(autoload 'xbacklight-white "xbacklight" "\
White screen." t)
(register-definition-prefixes "xbacklight" '("xbacklight-"))

;;; End of scraped data

(provide 'emacsvox-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacsvox-loaddefs.el ends here
